# After changing this file, check it on:
#   http://lint.travis-ci.org/


language: python
python:
    - 3.4

install:
    - python3 --version
    - python --version
    - time sudo apt-get update
    - travis_retry sudo apt-get install gir1.2-pango gir1.2-gtk xdg-utils librsvg2-common libglib2.0-dev intltool
    - travis_retry sudo apt-get install python3-gobject python3-gi python3-cairo python3-gi-cairo python3-bsddb3 python3-dev python3-nose 


    - travis_retry curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
    - sudo python get-pip.py
    - travis_retry sudo pip install pyicu==1.8
    - travis_retry sudo pip install mock

    - cd $TRAVIS_BUILD_DIR
    # $TRAVIS_BUILD_DIR is set to the location of the cloned repository:
    # for example: /home/travis/build/gramps-project/gramps
    - python setup.py build

#before_script:
#    - sudo Xvfb :99 -ac &
#    - export DISPLAY=:99

script:
    -  mkdir -p ~/.gramps/grampsdb/
    -  nosetests3 --exclude=TestcaseGenerator --exclude=vcard --exclude=merge_ref_test  gramps
