# After changing this file, check it on:
#   http://lint.travis-ci.org/


language: python
python:
    - 3.3
    - 3.4

install:
    - time sudo apt-get update
    - travis_retry sudo apt-get install python3-gobject python3-gi python3-cairo python3-gi-cairo gir1.2-pango gir1.2-gtk python3-bsddb3 xdg-utils librsvg2-common python3-dev libglib2.0-dev intltool python3-nose
    - travis_retry pip install django
    - travis_retry pip install pyicu
    - python setup.py build

script:
    -  DJANGO_SETTINGS_MODULE=gramps.webapp.settings  nosetests3 --exclude=TestcaseGenerator --exclude=exportvcard_test --exclude=plugins --exclude=vcard --exclude=merge_ref_test --exclude=test_util_test --exclude=cli_test --exclude=gramps.webapp --exclude=gen.test --exclude=widgets --exclude=gui gramps

